# Generated by Django 2.1.7 on 2019-02-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('images', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=255)),
                ('deskripsi1', models.TextField(max_length=1000)),
                ('deskripsi2', models.TextField(max_length=1000)),
                ('deskripsi3', models.TextField(max_length=1000)),
                ('deskripsi4', models.TextField(max_length=1000)),
                ('deskripsi5', models.TextField(max_length=1000)),
            ],
        ),
    ]
